services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/nutrition
      SPRING_DATASOURCE_USERNAME: nutrition_user
      SPRING_DATASOURCE_PASSWORD: 12345678Abc
    networks:
      - backend

  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_DATABASE: nutrition
      MYSQL_ROOT_PASSWORD: 12345678Abc
      MYSQL_USER: nutrition_user
      MYSQL_PASSWORD: 12345678Abc
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
